### ISSUE TITLE
touch dro

### ISSUE THREAD

**Issue by Traktorist3d** [pcm52/DRO-V6#1]
Hi, I have as5311 sensors and would like to repeat your design. But I would like to work with data through touch dro. Do you have any idea how you can use your project + touch dro?

**Comment by Olabec** [comment]
You don't need my project for touch DRO. The AS5311 has quadrature outputs. You could connect these directly to to their ESP32 based interface board as described on their website.

**Comment by Traktorist3d** [comment]
Well, what about your sensor boards, can I use them for this?

**Comment by Olabec** [comment]
Yes, the DRO-V6 board should work with the touch DRO interface.

**Comment by Traktorist3d** [comment]
It's great, but I can't figure it out. In the photo of your encoder, there is an as5311 chip on one board, and on the other side there are many more elements, including another microcircuit. But the diagram shows only as5311. I see a crystal oscillator and so on. Just a stock board from AMS - as5311-ab contains only AS5311 and some capacitors. And I don’t understand, should I take your fee as a basis or draw stock from AMS

**Comment by Olabec** [comment]
I think you are looking at an early version of the encoder on the PCM52.com site. Use the eagle sch and brd files here on github for encoder8. The early version has an additional LS7366 quad counter and crystal.

**Comment by Traktorist3d** [comment]
Yes, I opened it, thank you very much for the free access to your development. I will send the prints. The only thing that confuses me is only one hole in the board for fasteners. In the old version you had 4 holes. And minimal margins along the edges of the board for pressing against the case. After all, there will still be elements sticking out (capacitors, etc.), if I'm not mistaken, the sensors should all be rigid in the case for fine-grained data display. Or is one hole enough?

**Comment by Traktorist3d** [comment]
![2143](https://user-images.githubusercontent.com/109711913/212701850-e69685b0-6b7f-4c53-8237-20530a9e9fc6.JPG)
Is there a mistake in the screenshot? 5 volt wire not connected
